# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SemverOrder < Formula
  desc ""
  homepage "https://github.com/vidhill/homebrew-tools"
  version "0.0.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vidhill/semver-order-cli/releases/download/v0.0.4/semver-order-cli_0.0.4_Darwin_x86_64.tar.gz"
      sha256 "40345633d2c855012765073354b96af2664139f81a53e6e40576012585456b18"

      def install
        bin.install "semver-order"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vidhill/semver-order-cli/releases/download/v0.0.4/semver-order-cli_0.0.4_Darwin_arm64.tar.gz"
      sha256 "497bf1131d8f1863822ac7cd62c9c7bf9f04cb6fdb3b47f6ae93c15a2d0ce82b"

      def install
        bin.install "semver-order"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vidhill/semver-order-cli/releases/download/v0.0.4/semver-order-cli_0.0.4_Linux_arm64.tar.gz"
      sha256 "871e6bab95ec6e17e3f7409f499919c42b90b0ab27dbe21eee800671c1aed982"

      def install
        bin.install "semver-order"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/vidhill/semver-order-cli/releases/download/v0.0.4/semver-order-cli_0.0.4_Linux_x86_64.tar.gz"
      sha256 "9ddd5a2afef4d8c4f42fcbb5eab9c24bf4737408d371a098d7696fbc408ce81d"

      def install
        bin.install "semver-order"
      end
    end
  end
end
